### ISSUE TITLE
Can you publish it with npm?

### ISSUE THREAD

**Issue by galzil** [royby12/homebridge-switcherV2#1]
I'm using HOOBS and can't install the plugin (tried using the terminal but I get error messages)

**Comment by royby12** [comment]
Hi @galzil , can you copy the error message you get from the console?

**Comment by galzil** [comment]
`npm ERR! path git
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn git
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/royby12/homebridge-switcherV2.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent `

**Comment by liadb** [comment]
Hi, I'm also using homebridge on Docker and need it as a npm module to install it from the GUI

**Comment by orianlevy** [comment]
Unable to install with Hoobs, can you please publish with npm?

**Comment by javimoralez** [comment]
has anyone found a work around? I have the same issue when i'm trying to install the broadlink plugin, i'm also running homebridge with docker.
